image: ruby2.0.0
script:
  - cp spec/dummy/config/database.drone.yml spec/dummy/config/database.yml
  - bundle install
  - bundle exec rake db:setup
  - bundle exec rspec spec
services:
  - postgres
notify:
  email:
    recipients:
      - j@jipi.ca